baseURL = 'https://www.asymmetricalcollage.com/'
languageCode = 'en-us'
title = 'Asymmetrical Collage'

# Build settings
buildDrafts = false
buildFuture = false
canonifyURLs = true

# Parameters
[params]
    description = "Riding the waves of change through financial sovereignty, privacy, and security analysis"

  [params.social]
        twitter = "https://twitter.com/asymmetricalc"
        nostr = "https://njump.me/npub1m3qu40agsucj9mkvunvak7yhq86hlgu8sc7mf4w0fhahv0y859ts04zq5r"
        
# Taxonomies
[taxonomies]
    tag = "tags"
    category = "categories"

# Enable rendering of HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
