baseURL = 'https://www.asymmetricalcollage.com/'
languageCode = 'en-us'
title = 'Asymmetrical Collage'

# Build settings
buildDrafts = false
buildFuture = false
canonifyURLs = true

# Parameters
[params]
    description = "Riding the waves of change through financial sovereignty, privacy, and security analysis"
    images = ["/images/RSS.png"]

    [params.social]
        twitter = "https://twitter.com/asymmetricalc"

# Taxonomies
[taxonomies]
    tag = "tags"
    category = "categories"

# Enable rendering of HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true